spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seewo_easi_pass
#      username:
#      password:
#      host: sr-masaike.cn
#      port: 27017
#      database: seewo_easi_pass
#      username: masaike
#      password: masaike
